routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('logout', "Auth\LoginController@logout");
Route::get('home', function () {
    return redirect('/');
});
Route::group([
    'middleware' => ['web', 'auth']
], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('object', 'ControlObjectController');
    Route::get('object/{control_object}/render-table', 'ControlObjectController@renderTable')->name('object.render_table');
    Route::get('object/{control_object}/activate', 'ControlObjectController@activate')->name('object.activate');
    Route::get('object/{control_object}/deactivate', 'ControlObjectController@deactivate')->name('object.deactivate');
    Route::get('object/{control_object}/delete', 'ControlObjectController@destroy')->name('object.delete_get');
    Route::get('object-search', 'ControlObjectController@search')->name('object.search');
    Route::get('fetch-object/{control_object}', 'ControlObjectController@fetch')->name('object.fetch');

    Route::get('profile', "ProfileController@index")->name('profile.index');
    Route::get('profile/edit', "ProfileController@edit")->name('profile.edit');
    Route::put('profile', "ProfileController@update")->name('profile.update');

    Route::get('notifications', 'NotificationsController@index')->name('notifications.index');

    Route::get('statistics', 'StatisticsController@index')->name('statistics.index');
    Route::post('statistics', 'StatisticsController@process')->name('statistics.process');

    Route::view('/info', 'info');
    Route::view('/links', 'links');

    Route::get('reports', 'ReportsController@index')->name('reports.index');
    Route::post('reports/generate', 'ReportsController@generateAndDownload')->name('reports.generate');
    Route::get('reports/{id}', 'ReportsController@download')->name('reports.download');
});

resources/views/object/chart.blade.php
<script>
    window.onload = function() {

        var dataPoints = [];

        var chart = new CanvasJS.Chart("chartContainer{{$model->id}}", {
            theme: "light2",
            title: {
                text: "{{ $model->name . "( $model->unitSymbol )" }}"
            },
            data: [{
                type: "line",
                dataPoints: dataPoints
            }]
        });
        updateData();

// Initial Values
        var xValue = 0;
        var yValue = 10;
        var newDataCount = 6;

        function addData(data) {
            if(newDataCount != 1) {
                $.each(data, function(key, value) {

                    dataPoints.push({x: value[0], y: parseInt(value[1])});
                    xValue++;
                    yValue = parseInt(value[1]);
                });
            } else {
                //dataPoints.shift();
                dataPoints.push({x: data[0][0], y: parseInt(data[0][1])});
                xValue++;
                yValue = parseInt(data[0][1]);
            }

            newDataCount = 1;
            chart.render();
            setTimeout(updateData, 1500);
        }

        function updateData() {
            $.getJSON("/fetch-object/{{$model->id}}", addData);
            // $.getJSON("https://canvasjs.com/services/data/datapoints.php?xstart="+xValue+"&ystart="+yValue+"&length="+newDataCount+"type=json", addData);
        }

    }
</script>
<div id="chartContainer{{$model->id}}" style="height: 370px; max-width: 920px; margin: 0px auto;"></div>

resources/views/object/create.blade.php
@extends('layouts.app')

@section('content')


    <h3 class="page-title">Додати новий об'єкт керування</h3>
    <div class="row">
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Заповніть та підтвердіть форму нижче</h3>
                </div>
                <div class="panel-body">
                    <form action="{{ route('object.store') }}" method="post">

                        @include('helper.errors')

                        <div class="col-md-6">
                                {{ csrf_field() }}
                                <label for="name">Ім'я*</label>
                                <input type="text" name="name" value="{{ old('name') }}" placeholder="теплообмінник" required class="form-control">
                                <br>
                                <label for="description">Опис</label>
                                <input type="text" name="description" value="{{ old('description') }}" class="form-control" placeholder="короткий опис">
                                <br>
                                <label for="units">Одиниці виміру
                                    <select name="units" class="form-control" required>
                                        @foreach(\App\Models\ControlObject::getUnitsMap() as $value => $text)
                                                <option value="{{$value}}">{{ $text }}</option>
                                        @endforeach
                                    </select>
                                </label>
                                <br>
                                <label for="min_value">Мінімальне значення</label>
                                <input type="text" value="{{ old('min_value') }}" name="min_value" class="form-control" required placeholder="20">
                                <br>
                                <label for="max_value">Максимальне значення</label>
                                <input type="text" name="max_value" value="{{ old('max_value') }}" class="form-control" required placeholder="140">
                                <br>
                                <label for="active">Статус</label>
                                <label class="fancy-checkbox">
                                    <input name="active" type="checkbox" checked>
                                    <span>Активний</span>
                                </label>
                        </div>
                        <div class="col-md-6">
                            <label for="frequency">Періодичність замірів(в секундах)</label>
                            <input type="text" name="frequency" value="{{ old('frequency') }}" class="form-control" required>
                            <br>
                            <label for="accident_chance">Ймовірність спрацювання сигналізації(у %)</label>
                            <input type="text" name="accident_chance" value="{{ old('accident_chance') }}" class="form-control" required>
                            <br>
                            <label for="notification_channels[]">Канали оповіщень</label>
                            <label class="fancy-checkbox">
                                <input type="checkbox" value="\NotificationChannels\Telegram\TelegramChannel" name="notification_channels[]">
                                <span>Telegram</span>
                            </label>
                            <label class="fancy-checkbox">
                                <input type="checkbox" value="mail" checked name="notification_channels[]">
                                <span>Email</span>
                            </label>
                            <label class="fancy-checkbox">
                                <input type="checkbox" value="App\Notifications\Drivers\SmsChannel" name="notification_channels[]">
                                <span>SMS</span>
                            </label>
                            <br>
                            <button type="submit" class="btn btn-success">Зберегти</button>
                        </div>
                    </form>
                </div>
            </div>
    </div>


@endsection

resources/views/object/edit.blade.php
@extends('layouts.app')

@section('content')


    <h3 class="page-title">Редагувати {{ $model->name }}</h3>
    <div class="row">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Заповніть та підтвердіть форму нижче</h3>
            </div>
            <div class="panel-body">
                <form action="{{ route('object.update', $model->id) }}" method="post">

                    @include('helper.errors')

                    <div class="col-md-6">
                        {{ csrf_field() }}
                        {{ method_field('put') }}
                        <label for="name">Ім'я*</label>
                        <input type="text" name="name" value="{{ $model->name }}" required class="form-control">
                        <br>
                        <label for="description">Опис</label>
                        <input type="text" name="description" value="{{ $model->description ? $model->description : '' }}" class="form-control">
                        <br>
                        <label for="units">Одиниці виміру
                            <select name="units" class="form-control" required>
                                <option value="{{ $model->units }}" selected>{{ \App\Models\ControlObject::getUnitsMap()[$model->units] }}</option>
                                @foreach(\App\Models\ControlObject::getUnitsMap() as $value => $text)
                                    @if ($model->units != $value)
                                        <option value="{{$value}}">{{ $text }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </label>
                        <br>
                        <label for="min_value">Мінімальне значення</label>
                        <input type="text" value="{{ $model->min_value }}" name="min_value" class="form-control" required>
                        <br>
                        <label for="max_value">Максимальне значення</label>
                        <input type="text" name="max_value" value="{{ $model->max_value }}" class="form-control" required>
                        <br>
                        <label for="active">Статус</label>
                        <label class="fancy-checkbox">
                            <input name="active" type="checkbox" {{ $model->active ? 'checked' : '' }}>
                            <span>Активний</span>
                        </label>
                    </div>
                    <div class="col-md-6">
                        <label for="frequency">Періодичність замірів(в секундах)</label>
                        <input type="text" name="frequency" value="{{ $model->frequency }}" class="form-control" required>
                        <br>
                        <label for="accident_chance">Ймовірність спрацювання сигналізації(у %)</label>
                        <input type="text" name="accident_chance" value="{{ $model->accident_chance }}" class="form-control" required>
                        <br>
                        <label for="notification_channels[]">Канали оповіщень</label>
                        <label class="fancy-checkbox">
                            <input type="checkbox" @if($model->hasChannel('\NotificationChannels\Telegram\TelegramChannel')) checked @endif  value="\NotificationChannels\Telegram\TelegramChannel" name="notification_channels[]">
                            <span>Telegram</span>
                        </label>
                        <label class="fancy-checkbox">
                            <input type="checkbox" value="mail" @if($model->hasChannel('mail')) checked @endif name="notification_channels[]">
                            <span>Email</span>
                        </label>
                        <label class="fancy-checkbox">
                            <input type="checkbox" value="App\Notifications\Drivers\SmsChannel" @if($model->hasChannel('App\Notifications\Drivers\SmsChannel')) checked @endif name="notification_channels[]">
                            <span>SMS</span>
                        </label>
                        <br>
                        <button type="submit" class="btn btn-success">Оновити</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


@endsection

resources/views/object/index.blade.php
@extends('layouts.app')

@section('content')

    <h3 class="page-title">Об'єкти керувань</h3>
    <div class="row">
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">В порядку спадання дати добавлення</h3>
                </div>
                <div class="panel-body">
                    <p>
                        <a href="{{ route('object.create') }}">
                            <button type="button" class="btn btn-primary right">Додати</button>
                        </a>
                    </p>
                    @if($models->isEmpty())
                        Немає записів
                    @else
                        @include('object.table')
                    @endif
                </div>
            </div>
    </div>

@endsection

resources/views/object/result_rows.blade.php
@foreach($model->results->sortByDesc('created_at') as $result)
    <tr class="{{ $result->out_of_range ? 'danger' : ''  }}">
        <td>{{++$loop->index}}</td>
        <td>{{$result->value}}</td>
        <td>{{$result->created_at}}</td>
    </tr>
@endforeach

resources/views/object/show.blade.php
@extends('layouts.app')

@section('content')

    <h3 class="page-title">{{ $model->name }}</h3>
    <div class="row">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title"><b>Опис:</b> {{ $model->description }}</h3>
            </div>
            <div class="panel-body">
                <h3>Результати</h3>
                @if($model->results->isEmpty())
                    Поки не було зроблено жодного зняття показників
                @else
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Значення ({{\App\Models\ControlObject::getUnitsMap()[$model->units]}})</th>
                            <th>Дата</th>
                        </tr>
                        </thead>
                        <tbody id="rows">
                            @include('object.result_rows')
                        </tbody>
                    </table>
                @endif
            </div>
            <div id="field" class="hidden" data-field-id="{{$model->id}}" ></div>
        </div>
    </div>
    <script>
        var fieldId = $('#field').data("field-id");
        function sleep (time) {
            return new Promise((resolve) => setTimeout(resolve, time));
        }
        function render() {

            $.ajax(
                {
                    url: "/object/" + fieldId + "/render-table",
                    success: function(result){
                        $("#rows").html(result);
                    }
                });

            sleep(1000).then(() => {
                render();
            });

        }

        render();
    </script>

@endsection

resources/views/object/table.blade.php
<table class="table table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>Назва</th>
        <th>Опис</th>
        <th>Зроблено замірів</th>
        <th>Аварійних ситуацій</th>
        <th>Періодичність моніторингу</th>
        <th>Активний</th>
        <th width="125px">Дії</th>
    </tr>
    </thead>
    <tbody>
    @foreach($models as $id => $model)
        <tr class="{{ $model->active ?: 'warning' }}">
            <td>{{++$id}}</td>
            <td>{{$model->name}}</td>
            <td>{{$model->description}}</td>
            <td>{{$model->results()->count()}}</td>
            <td>{{$model->results()->outOfRange()->count()}}</td>
            <td>{{$model->frequency}} с.</td>
            <td>{{$model->active ? 'Так' : 'Ні'}}</td>
            <td>
                @if ($model->active)
                    <a href="{{ route('object.deactivate', $model->id) }}" title="Деактивувати">
                        <i class="fa fa-fw fa-check"></i>
                    </a>
                @else
                    <a href="{{ route('object.activate', $model->id) }}" title="Активувати">
                        <i class="fa fa-fw fa-check"></i>
                    </a>
                @endif
                <a href="{{ route('object.show', $model->id) }}" title="Детальніше">
                    <i class="fa fa-fw fa-eye"></i>
                </a>
                <a href="{{ route('object.edit', $model->id) }}" title="Редагувати">
                    <i class="fa fa-fw fa-edit"></i>
                </a>
                <a id="delete_object" href="{{ route('object.delete_get', $model->id) }}" title="Видалити">
                    <i class="fa fa-fw fa-trash"></i>
                </a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
<script>
    $("#delete_object").click(function (e) {
        e.preventDefault();
        if (confirm("Ви впевнені, що хочете видалити цей об'єкт керування? Також будуть видалені всі записи про минулі заміри")) {
            window.location.href = $(this).attr('href');
        }
    })
</script>