routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('logout', "Auth\LoginController@logout");
Route::get('home', function () {
    return redirect('/');
});
Route::group([
    'middleware' => ['web', 'auth']
], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('object', 'ControlObjectController');
    Route::get('object/{control_object}/render-table', 'ControlObjectController@renderTable')->name('object.render_table');
    Route::get('object/{control_object}/activate', 'ControlObjectController@activate')->name('object.activate');
    Route::get('object/{control_object}/deactivate', 'ControlObjectController@deactivate')->name('object.deactivate');
    Route::get('object/{control_object}/delete', 'ControlObjectController@destroy')->name('object.delete_get');
    Route::get('object-search', 'ControlObjectController@search')->name('object.search');
    Route::get('fetch-object/{control_object}', 'ControlObjectController@fetch')->name('object.fetch');

    Route::get('profile', "ProfileController@index")->name('profile.index');
    Route::get('profile/edit', "ProfileController@edit")->name('profile.edit');
    Route::put('profile', "ProfileController@update")->name('profile.update');

    Route::get('notifications', 'NotificationsController@index')->name('notifications.index');

    Route::get('statistics', 'StatisticsController@index')->name('statistics.index');
    Route::post('statistics', 'StatisticsController@process')->name('statistics.process');

    Route::view('/info', 'info');
    Route::view('/links', 'links');

    Route::get('reports', 'ReportsController@index')->name('reports.index');
    Route::post('reports/generate', 'ReportsController@generateAndDownload')->name('reports.generate');
    Route::get('reports/{id}', 'ReportsController@download')->name('reports.download');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">

<head>
    <title>Система моніторингу об'єктів керувань</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/linearicons/style.css') }}">
    <link rel="stylesheet" href="{{ asset("vendor/chartist/css/chartist-custom.css") }}">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{{ asset("css/main.css") }}">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="{{ asset("css/demo.css") }}">
    <!-- GOOGLE FONTS -->
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
    <link href="{{ asset("css/fonts.css") }}" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('img/apple-icon.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ asset('img/favicon.png') }}">
</head>

<body>
<!-- WRAPPER -->
<div id="wrapper">
    <!-- NAVBAR -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="brand">
            <a href="{{ route('home') }}"><i class="fa fa-desktop" style="font-size:20px;"> ІХФ</i></a>
        </div>
        <div class="container-fluid">
            <div class="navbar-btn">
                <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
            </div>
            <form class="navbar-form navbar-left" action="{{ route('object.search') }}" method="get">
                <div class="input-group">
                    <input type="text" name="text" value="" class="form-control" placeholder="пошук по об'єктам...">
                    <span class="input-group-btn"><button type="submit" class="btn btn-primary">Шукати</button></span>
                </div>
            </form>
            <div class="navbar-btn navbar-btn-right">
                <a class="btn btn-success update-pro" href="http://ihf.kpi.ua/" title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span>Сайт ІХФ</span></a>
            </div>
            <div id="navbar-menu">
                <ul class="nav navbar-nav navbar-right">
                    @if (Auth::check())
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                                <i class="lnr lnr-alarm"></i>
                                @if (Auth::user()->unreadNotifications()->count())
                                    <span class="badge bg-danger">{{ Auth::user()->unreadNotifications()->count() }}</span>
                                @endif
                            </a>
                            <ul class="dropdown-menu notifications">
                                @foreach(Auth::user()->unreadNotifications->take(5) as $notification)
                                    <li><a href="#" class="notification-item"><span class="dot bg-danger"></span>{{ $notification->data['message'] }}</a></li>
                                @endforeach
                                <li><a href="{{ route('notifications.index') }}" class="more">Переглянути всі оповіщення</a></li>
                            </ul>
                        </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="lnr lnr-question-circle"></i> <span>Допомога</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url('info') }}">Про систему</a></li>
                            <li><a href="{{ url('links') }}">Корисні посилання</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{{ asset('img/user.png') }}" class="img-circle" alt="Avatar"> <span>{{ Auth::user()->name }}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('profile.index') }}"><i class="lnr lnr-user"></i> <span>Мій профіль</span></a></li>
                            <li><a href="{{ url('/logout') }}"><i class="lnr lnr-exit"></i> <span>Вийти</span></a></li>
                        </ul>
                    </li>
                @endif
                <!-- <li>
                        <a class="update-pro" href="https://www.themeineed.com/downloads/klorofil-pro-bootstrap-admin-dashboard-template/?utm_source=klorofil&utm_medium=template&utm_campaign=KlorofilPro" title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span>UPGRADE TO PRO</span></a>
                    </li> -->
                </ul>
            </div>
        </div>
    </nav>
    <!-- END NAVBAR -->
    <!-- LEFT SIDEBAR -->
    <div id="sidebar-nav" class="sidebar">
        <div class="sidebar-scroll">
            <nav>
                <ul class="nav">
                    <li><a href="{{ route('home') }}" class="@if(route('home') == URL::current()) active @endif"><i class="lnr lnr-home"></i> <span>Головна</span></a></li>
                    <li><a href="{{ route('object.index') }}" class="@if(route('object.index') == URL::current()) active @endif"><i class="lnr lnr-cog"></i> <span>Об'єкти керувань</span></a></li>
                    <li><a href="{{ route('statistics.index') }}" class="@if(route('statistics.index') == URL::current()) active @endif"><i class="lnr lnr-chart-bars"></i> <span>Статистика</span></a></li>
                    <li><a href="{{ route('reports.index') }}" class="@if(route('reports.index') == URL::current()) active @endif"><i class="lnr lnr-file-empty"></i> <span>Звіти</span></a></li>
                    <li><a href="{{ route('notifications.index') }}" class="@if(route('notifications.index') == URL::current()) active @endif"><i class="lnr lnr-alarm"></i> <span>Оповіщення</span></a></li>
                </ul>
            </nav>
        </div>
    </div>
    <!-- END LEFT SIDEBAR -->
    <!-- MAIN -->
    <div class="main">
        <!-- MAIN CONTENT -->
        <div class="main-content">
            <div class="container-fluid">
                @include('helper.flash_messages')
                @yield('content')
            </div>
        </div>
        <!-- END MAIN CONTENT -->
    </div>
    <!-- END MAIN -->
    <div class="clearfix"></div>
    <footer>
        <div class="container-fluid">
            <p class="copyright">&copy; 2018 <a href="https://www.linkedin.com/in/dima-korets/" target="_blank">Korets D</a>. Всі права захищені.</p>
        </div>
    </footer>
</div>
<!-- END WRAPPER -->
<!-- Javascript -->
<script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/canvas.min.js') }}"></script>
<script src="{{ asset('vendor/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js') }}"></script>
<script src="{{ asset('vendor/chartist/js/chartist.min.js') }}"></script>
<script src="{{ asset('scripts/klorofil-common.js') }}"></script>
<script>
    $(function() {
        var data, options;

        // headline charts
        data = {
            labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            series: [
                [23, 29, 24, 40, 25, 24, 35],
                [14, 25, 18, 34, 29, 38, 44],
            ]
        };

        options = {
            height: 300,
            showArea: true,
            showLine: false,
            showPoint: false,
            fullWidth: true,
            axisX: {
                showGrid: false
            },
            lineSmooth: false,
        };

        new Chartist.Line('#headline-chart', data, options);


        // visits trend charts
        data = {
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            series: [{
                name: 'series-real',
                data: [200, 380, 350, 320, 410, 450, 570, 400, 555, 620, 750, 900],
            }, {
                name: 'series-projection',
                data: [240, 350, 360, 380, 400, 450, 480, 523, 555, 600, 700, 800],
            }]
        };

        options = {
            fullWidth: true,
            lineSmooth: false,
            height: "270px",
            low: 0,
            high: 'auto',
            series: {
                'series-projection': {
                    showArea: true,
                    showPoint: false,
                    showLine: false
                },
            },
            axisX: {
                showGrid: false,

            },
            axisY: {
                showGrid: false,
                onlyInteger: true,
                offset: 0,
            },
            chartPadding: {
                left: 20,
                right: 20
            }
        };

        new Chartist.Line('#visits-trends-chart', data, options);


        // visits chart
        data = {
            labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
            series: [
                [6384, 6342, 5437, 2764, 3958, 5068, 7654]
            ]
        };

        options = {
            height: 300,
            axisX: {
                showGrid: false
            },
        };

        new Chartist.Bar('#visits-chart', data, options);


        // real-time pie chart
        var sysLoad = $('#system-load').easyPieChart({
            size: 130,
            barColor: function(percent) {
                return "rgb(" + Math.round(200 * percent / 100) + ", " + Math.round(200 * (1.1 - percent / 100)) + ", 0)";
            },
            trackColor: 'rgba(245, 245, 245, 0.8)',
            scaleColor: false,
            lineWidth: 5,
            lineCap: "square",
            animate: 800
        });

        var updateInterval = 3000; // in milliseconds

        setInterval(function() {
            var randomVal;
            randomVal = getRandomInt(0, 100);

            sysLoad.data('easyPieChart').update(randomVal);
            sysLoad.find('.percent').text(randomVal);
        }, updateInterval);

        function getRandomInt(min, max) {
            return Math.floor(Math.random() * (max - min + 1)) + min;
        }

    });
</script>
</body>

</html>